
POST {{baseUrl}}/option/introduce
Content-Type: application/json
Authorization: {{jwt}}

{
  "furnitureId": 7
}
###

PATCH {{baseUrl}}/option/cancel/1
Content-Type: application/json
Authorization: {{jwt}}
###

GET {{baseUrl}}/options/
Authorization: {{jwt}}
###

GET {{baseUrl}}/options/me
Authorization: {{jwt}}
###