
GET {{baseUrl}}/photos/homePage
###

POST {{baseUrl}}/photos/add
Authorization: {{jwt}}
Content-Type: application/json

{
  "furnitureId": 1,
  "source": "source"
}
###

GET {{baseUrl}}/photos/favourite/1
###