
GET {{baseUrl}}/photos/homePage
###

PATCH {{baseUrl}}/photos/visibility/1
Content-Type: application/json
Authorization: {{jwt}}

{
  "visibility": true
}
###

PATCH {{baseUrl}}/photos/visibility/1
Content-Type: application/json
Authorization: {{jwt}}

{
  "visibility": false
}
###

PATCH {{baseUrl}}/photos/homePage/1
Content-Type: application/json
Authorization: {{jwt}}

{
  "onHomePage": false
}
###

PATCH {{baseUrl}}/photos/homePage/1
Content-Type: application/json
Authorization: {{jwt}}

{
  "onHomePage": true
}
###