
GET {{baseUrl}}/requestForVisit/
Authorization: {{jwt}}
###

GET {{baseUrl}}/requestForVisit/me
Authorization: {{takeover_jwt}}
###

PATCH {{baseUrl}}/requestForVisit/cancel/1
Authorization: {{jwt}}
###

PATCH {{baseUrl}}/requestForVisit/accept/1
Authorization: {{jwt}}
###