// login as 'other' (pwd : azerty) -> fail (no user found)
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "other",
  "password": "azerty"
}
###

//login as 'ex' (pwd : qwerty) -> fail (invalid pwd)
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "ex",
  "password": "qwerty"
}
###

//login as 'ex' (pwd : azerty) -> success
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "azerty",
  "rememberMe": true
}

> {%
 client.global.set("jwt", response.body.token);
 %}
###

GET {{baseUrl}}/users/me
Authorization: {{jwt}}

###