POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "other",
  "password": "azerty"
}

### /login as 'other' (pwd : azerty) -> fail (no user found)


POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "ex",
  "password": "qwerty"
}

### /login as 'ex' (pwd : qwerty) -> fail (invalid pwd)


POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "ex",
  "password": "azerty",
  "rememberMe": true
}

### /login as 'ex' (pwd : azerty) -> success@@
##should faild because =>
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "username": "a",
  "lastName": "b",
  "firstName": "c",
  "email": "d@gmail.com",
  "password": "<p>hello</p>",
  "role": "client",
  "address": {
    "street": "f",
    "buildingNumber": "g",
    "unitNumber": "h",
    "postcode": 1,
    "commune": "j",
    "country": "q"
  }
}